# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4c03c15094b544e4649c918ee1d2142fad452574af58ed4e160bea2fcb90420b9cc84ff35ab192d81bda9ab102c85237b0fe5e0e46da6825ef3b644c119fe93

test:
  secret_key_base: 61067556d4a2edd97833bfe3ee9b4837a33b501fb336ed9ce2e33874a690089b9215aa50dc9305fcc5107d7b999e30b3c4e2bc06f584bcc10c6fcfe6f8c33206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
